<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTlrtzxi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTlrtzxi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerTlrtzxi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerTlrtzxi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerTlrtzxi\appDevDebugProjectContainer([
    'container.build_hash' => 'Tlrtzxi',
    'container.build_id' => 'a55707e3',
    'container.build_time' => 1576623648,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTlrtzxi');
